import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#393939",
        "on-error-container": "#ffdad6",
        "surface-dim": "#131313",
        "on-surface": "#e2e2e2",
        "on-secondary-fixed-variant": "#3c3b3b",
        "on-tertiary": "#1a1c1c",
        primary: "#ffffff",
        "primary-container": "#d4d4d4",
        "on-secondary-container": "#e5e2e1",
        "surface-container-low": "#1b1b1b",
        "primary-fixed": "#5d5f5f",
        outline: "#919191",
        surface: "#131313",
        "tertiary-container": "#909191",
        secondary: "#c8c6c5",
        "on-secondary": "#1b1c1c",
        "secondary-fixed": "#c8c6c5",
        "on-surface-variant": "#c6c6c6",
        "on-tertiary-container": "#000000",
        "on-primary": "#1a1c1c",
        "inverse-on-surface": "#303030",
        "surface-container-highest": "#353535",
        "on-secondary-fixed": "#1b1c1c",
        "primary-fixed-dim": "#454747",
        tertiary: "#e3e2e2",
        "inverse-primary": "#5d5f5f",
        "tertiary-fixed": "#5e5e5f",
        "on-primary-fixed": "#ffffff",
        "on-error": "#690005",
        "on-background": "#e2e2e2",
        "error-container": "#93000a",
        "tertiary-fixed-dim": "#464747",
        "surface-variant": "#353535",
        "secondary-fixed-dim": "#adabaa",
        error: "#ffb4ab",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-fixed-variant": "#e3e2e2",
        "surface-tint": "#c6c6c7",
        "outline-variant": "#474747",
        "on-tertiary-fixed": "#ffffff",
        "inverse-surface": "#e2e2e2",
        background: "#131313",
        "surface-container": "#1f1f1f",
        "on-primary-container": "#000000",
        "secondary-container": "#474746",
        "surface-container-high": "#2a2a2a",
        "on-primary-fixed-variant": "#e2e2e2",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-inter)", "sans-serif"],
        body: ["var(--font-manrope)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
      },
      animation: {
        ticker: "ticker 30s linear infinite",
      },
      keyframes: {
        ticker: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
      maxWidth: {
        "screen-3xl": "1920px",
      },
    },
  },
  plugins: [],
};

export default config;
