/**
 * Reads the pre-rendered project shell page and generates a TypeScript
 * module that exports the HTML as a string constant.
 * Run AFTER `next build` and BEFORE `wrangler deploy`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const shellPath = resolve(root, "out/work/obsidian-echoes.html");
const outPath = resolve(root, "shell.ts");

const html = readFileSync(shellPath, "utf-8");

writeFileSync(
  outPath,
  `// Auto-generated by scripts/generate-shell.mjs — do not edit.\nexport const SHELL_HTML = ${JSON.stringify(html)};\n`,
);

console.log(`✅ shell.ts generated (${html.length} chars)`);
